### ISSUE TITLE
get good lol

### ISSUE THREAD

**Issue by mebrooks01** [mebrooks01/Mars-Bot#1]
Make the bot not crappy

**Comment by XboxBedrock** [comment]
lmao

**Comment by mebrooks01** [comment]
shut up

**Comment by XboxBedrock** [comment]
:(

**Comment by XboxBedrock** [comment]
wait github webhook actually forwards closed issues

**Comment by mebrooks01** [comment]
yes

**Comment by mebrooks01** [comment]
@all-contributors add @mebrooks01 Shitty ass code

**Comment by mebrooks01** [comment]
@all-contributors add @mebrooks01 Shitty ass code

**Comment by mebrooks01** [comment]
@all-contributors add @Mr-Smarty anti shitty ass code

**Comment by mebrooks01** [comment]
@all-contributors add @Mr-Smarty anti shitty ass code

**Comment by mebrooks01** [comment]
@all-contributors add @XboxBedrock  anti shitty ass code

**Comment by mebrooks01** [comment]
@all-contributors add @cAtte anti shitty ass code

**Comment by XboxBedrock** [comment]
well get good lol is in progress I see

**Comment by mebrooks01** [comment]
@all-contributors add @cAttte anti shitty ass code

**Comment by mebrooks01** [comment]
@all-contributors add @cAttte anti shitty ass code

**Comment by mebrooks01** [comment]
@all-contributors add @rudeyeti anti shitty ass code

**Comment by mebrooks01** [comment]
@all-contributors add @rudeyeti anti shitty ass code

**Comment by mebrooks01** [comment]
@all-contributors add @mebrooks01 📖

**Comment by mebrooks01** [comment]
@all-contributors add @mebrooks01 Documentation

**Comment by mebrooks01** [comment]
@all-contributors add @Vaporrrr anti shitty ass code

**Comment by rudeyeti** [comment]
Awesome!

**Comment by mebrooks01** [comment]
@rudeyeti its not dm advertising if its not in a DM [https://discord.gg/SwzQUKYK](https://discord.gg/SwzQUKYK )

**Comment by XboxBedrock** [comment]
lol
